export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_REQUEST";
export const ADD_ITEM_FAILURE = "ADD_ITEM_REQUEST";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const ADD_NEW_QUANTITY = "ADD_NEW_QUANTITY";
export const DELETE_QUANTITY = "DELETE_QUANTITY";
